# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
    # Runs a set of commands using the runners shell
    - uses: actions/checkout@master
    - name: Copy via ssh
      uses: garygrossgarten/github-action-scp@release
      with:
        local: /
        remote: /home/gptbot
        host: bot.kaveenk.com
        username: root
        password: ${{ secrets.SSH_PASS }}
    - name: Restart bot!
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd /home/gptbot
          kill -9 $(cat bot.pid)
          rm bot.pid
          screen -dmS GPTBot python3.9 main.py
          logout
          exit
        host: bot.kaveenk.com
        user: root
        pass: ${{ secrets.SSH_PASS}}
